name: Python package

on:
  push:
    branches:
      - hw05-main

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        #python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pylint
          pip install moto
          pip install boto3
      - name: Analyzing the code with pylint
        run: |
          pylint --fail-under=9.3 $(git ls-files 'hw05/*.py')
      - name: Run all your pytest tests in your code
        run: |
          pytest hw05
